// app/components/ui/Card.vue
<script setup lang="ts">
import type { PrimitiveProps } from 'reka-ui'
import { Primitive } from 'reka-ui'
import { tv } from 'tailwind-variants'

const card = tv({ base: 'border border-line-2 bg-surface p-6' })

const props = withDefaults(
    defineProps<PrimitiveProps & { class?: unknown }>(),
    { as: 'div' },
)
</script>

<template>
    <Primitive
        :as="as"
        :as-child="asChild"
        :class="card({ class: props.class as string })"
    >
        <slot />
    </Primitive>
</template>

// design-system/src/components/Card.tsx
import type { ReactNode } from 'react'
import { tv } from 'tailwind-variants'

import type { PrimitiveProps } from '../lib/primitive'
import { Primitive } from '../lib/primitive'

const card = tv({ base: 'border border-line-2 bg-surface p-6' })

/** The standard surface container: hairline border, raised surface, 24px padding. */
export interface CardProps extends PrimitiveProps {
    className?: string
    children?: ReactNode
}

export function Card({ as = 'div', className, ...rest }: CardProps) {
    return (
        <Primitive
            as={as}
            className={card({ className })}
            {...rest}
        />
    )
}
