// src/lib/ui/Select.svelte
<script lang="ts" module>
	export type SelectOption = {
		value: string;
		label: string;
		disabled?: boolean;
	};
</script>

<script lang="ts">
	import type { ClassValue } from 'svelte/elements';
	import { fade } from 'svelte/transition';
	import { Select } from 'bits-ui';
	import Field from '$lib/ui/Field.svelte';
	import SheetHeader from '$lib/ui/SheetHeader.svelte';
	import CaretDown from '$lib/ui/icons/CaretDown.svelte';
	import Check from '$lib/ui/icons/Check.svelte';
	import { registerOverlay } from '$lib/ui/overlays';
	import { wideViewport } from '$lib/ui/viewport';

	type Props = {
		label: string;
		items: SelectOption[];
		value?: string | string[];
		type?: 'single' | 'multiple';
		error?: string;
		placeholder?: string;
		disabled?: boolean;
		class?: ClassValue;
	};

	let {
		label,
		items,
		value = $bindable(),
		type = 'single',
		error,
		placeholder = 'Choose',
		disabled = false,
		class: klass
	}: Props = $props();

	let open = $state(false);

	$effect(() => (open ? registerOverlay(() => (open = false)) : undefined));

	const selected = $derived(
		type === 'multiple'
			? items.filter((item) => Array.isArray(value) && value.includes(item.value))
			: items.filter((item) => item.value === value)
	);

	const display = $derived(selected.map((item) => item.label).join(', '));
</script>

{#snippet trigger(id: string, describedBy: string | undefined, invalid: true | undefined)}
	<Select.Trigger
		{id}
		aria-invalid={invalid}
		aria-describedby={describedBy}
		class={[
			'field-box field-trigger min-h-row focus-ring',
			error ? 'border-danger' : 'border-line'
		]}
	>
		<span class={['truncate', !display && 'text-ink-faint']}>{display || placeholder}</span>
		<CaretDown size={18} class="shrink-0 text-ink-muted" />
	</Select.Trigger>
{/snippet}

{#snippet list()}
	<Select.Viewport class="min-h-0 flex-1 overflow-y-auto p-2">
		{#each items as item (item.value)}
			<Select.Item
				value={item.value}
				label={item.label}
				disabled={item.disabled}
				class="flex min-h-row w-full items-center gap-3 rounded-xl px-3 text-base font-bold
					select-none data-disabled:pointer-events-none data-disabled:opacity-50
					data-highlighted:bg-hover"
			>
				{#snippet children({ selected: isSelected })}
					<span class="min-w-0 flex-1 truncate">{item.label}</span>
					{#if isSelected}
						<Check size={20} class="shrink-0 text-accent-text" />
					{/if}
				{/snippet}
			</Select.Item>
		{/each}
	</Select.Viewport>
{/snippet}

{#snippet panel()}
	{#if wideViewport.current}
		<Select.Portal>
			<Select.Content
				sideOffset={6}
				class="overlay-menu max-h-[min(20rem,var(--bits-select-content-available-height))]
					min-w-(--bits-select-anchor-width)"
			>
				{@render list()}
			</Select.Content>
		</Select.Portal>
	{:else}
		<Select.Portal>
			<!-- Select has no Overlay part, so the scrim is ours — and so is its
			     lifetime. `Select.Portal` is only a portal: it mounts its children
			     whether or not the list is open, and it is `ContentStatic` that Bits
			     UI gates on presence. Without this `{#if}` the scrim sits over the
			     page permanently, which is exactly how it first shipped.

			     Svelte's own fade rather than the `[data-starting-style]` hooks
			     `overlay-scrim` reads, because Bits UI sets those on parts it owns
			     and this is not one. The duration matches the utility's. -->
			{#if open}
				<div class="overlay-scrim" transition:fade={{ duration: 180 }}></div>
			{/if}

			<Select.ContentStatic class="overlay-panel overlay-sheet">
				<SheetHeader title={label} />
				{@render list()}
			</Select.ContentStatic>
		</Select.Portal>
	{/if}
{/snippet}

<Field {label} {error} class={klass}>
	{#snippet children({ id, describedBy, invalid })}
		{#if type === 'multiple'}
			<Select.Root
				type="multiple"
				{items}
				{disabled}
				bind:open
				bind:value={() => (Array.isArray(value) ? value : []), (next) => (value = next)}
			>
				{@render trigger(id, describedBy, invalid)}
				{@render panel()}
			</Select.Root>
		{:else}
			<Select.Root
				type="single"
				{items}
				{disabled}
				bind:open
				bind:value={() => (typeof value === 'string' ? value : ''), (next) => (value = next)}
			>
				{@render trigger(id, describedBy, invalid)}
				{@render panel()}
			</Select.Root>
		{/if}
	{/snippet}
</Field>

// design-system/src/components/Select.tsx
import { tv } from 'tailwind-variants'
import * as RadixSelect from '@radix-ui/react-select'

import { IconCheck, IconChevronDown } from '../lib/icons'

const select = tv({
    slots: {
        trigger:
            'inline-flex w-full items-center justify-between gap-2 border border-line-2 bg-surface px-[13px] py-[11px] text-body-lg text-ink capitalize transition-[border-color] duration-[120ms] hover:border-accent',
        value: 'truncate',
        // Sizes the panel to its trigger and to the room below it. The Vue
        // original reads the same values off reka's `--reka-*` vars; Radix
        // publishes them under `--radix-*`, so the names differ by necessity.
        content:
            'z-[60] max-h-[var(--radix-select-content-available-height)] min-w-[var(--radix-select-trigger-width)] overflow-hidden border border-line-2 bg-canvas shadow-[0_24px_60px_-20px_rgba(0,0,0,0.7)]',
        viewport: 'p-[5px]',
        item: 'flex items-center justify-between gap-2.5 px-[11px] py-[9px] text-body text-ink-2 capitalize outline-none select-none data-highlighted:bg-surface-2 data-highlighted:text-ink data-[state=checked]:text-accent-ink',
    },
    variants: {
        // The placeholder is not a value, so it keeps its own casing.
        placeholder: { true: { value: 'text-ink-3 normal-case' } },
        // Only labels we derived from a bare value get title-cased. An explicit
        // `label` is human-authored and must survive verbatim, or
        // 'English (UK)' renders as 'English (Uk)'.
        authored: { true: { value: 'normal-case', item: 'normal-case' } },
    },
})

export type SelectOption = { label: string; value: string; disabled?: boolean }

/**
 * Single-choice dropdown. `items` accepts bare strings or `{label, value}`
 * objects; values are capitalised by the trigger, the placeholder is not.
 */
export interface SelectProps {
    items: readonly (string | SelectOption)[]
    value?: string
    onValueChange?: (value: string) => void
    placeholder?: string
}

export function Select({
    items,
    value,
    onValueChange,
    placeholder,
}: SelectProps) {
    const options = items.map((item) =>
        typeof item === 'object' ?
            { ...item, authored: true }
        :   {
                label: item,
                value: item,
                disabled: undefined,
                authored: false,
            },
    )

    // Render the label ourselves rather than relying on the headless component's
    // internal registry, which only resolves once the listbox has been opened.
    const current = options.find((o) => o.value === value)
    const currentLabel = current?.label

    const slots = select({
        placeholder: currentLabel == null,
        authored: current?.authored ?? false,
    })

    return (
        <RadixSelect.Root
            value={value}
            onValueChange={onValueChange}
        >
            <RadixSelect.Trigger className={slots.trigger()}>
                <span className={slots.value()}>
                    {currentLabel ?? placeholder ?? 'Select…'}
                </span>
                <IconChevronDown
                    size={16}
                    className='flex-none text-ink-3'
                />
            </RadixSelect.Trigger>
            <RadixSelect.Portal>
                <RadixSelect.Content
                    className={slots.content()}
                    position='popper'
                    sideOffset={6}
                >
                    <RadixSelect.Viewport className={slots.viewport()}>
                        {options.map((option) => (
                            <RadixSelect.Item
                                key={option.value}
                                value={option.value}
                                disabled={option.disabled}
                                // Casing is per-row: a list can mix derived and
                                // authored labels.
                                className={select({
                                    authored: option.authored,
                                }).item()}
                            >
                                <RadixSelect.ItemText>
                                    {option.label}
                                </RadixSelect.ItemText>
                                <RadixSelect.ItemIndicator>
                                    <IconCheck
                                        size={15}
                                        className='flex-none text-accent-ink'
                                    />
                                </RadixSelect.ItemIndicator>
                            </RadixSelect.Item>
                        ))}
                    </RadixSelect.Viewport>
                </RadixSelect.Content>
            </RadixSelect.Portal>
        </RadixSelect.Root>
    )
}
