// design-system/src/components/MatchedLabel.tsx
import { Highlight } from './Highlight'

/**
 * A search result's label with its fuzzy-matched characters marked, plus the
 * alternate keyword in parentheses when the hit came from one (e.g. an exercise
 * alias). The keyword half is only rendered when `keyword` is non-empty, and it
 * is dimmed one step (`text-ink-3`) and one size down from the label.
 */
export interface MatchedLabelProps {
    label: string
    labelPositions?: readonly number[]
    keyword?: string
    keywordPositions?: readonly number[]
}

export function MatchedLabel({
    label,
    labelPositions = [],
    keyword = '',
    keywordPositions = [],
}: MatchedLabelProps) {
    return (
        <>
            <Highlight
                text={label}
                positions={labelPositions}
            />
            {keyword ?
                <>
                    {' '}
                    <span className='text-body-sm text-ink-3'>
                        {'('}
                        <Highlight
                            text={keyword}
                            positions={keywordPositions}
                        />
                        {')'}
                    </span>
                </>
            :   null}
        </>
    )
}

// app/components/ui/MatchedLabel.vue
<script lang="ts">
import { defineComponent, h } from 'vue'

import UiHighlight from './Highlight.vue'

// A search result's label with its fuzzy-matched characters marked, plus the
// alternate keyword in parentheses when the hit came from one (e.g. an exercise
// alias). Render-function for the same reason as UiHighlight: the parens sit
// inline against the keyword, so a stray whitespace node would split them off.
export default defineComponent({
    name: 'UiMatchedLabel',
    props: {
        label: { type: String, required: true },
        labelPositions: {
            type: Array as () => readonly number[],
            default: () => [],
        },
        keyword: { type: String, default: '' },
        keywordPositions: {
            type: Array as () => readonly number[],
            default: () => [],
        },
    },
    setup(props) {
        return () => [
            h(UiHighlight, {
                text: props.label,
                positions: props.labelPositions,
            }),
            ...(props.keyword ?
                [
                    ' ',
                    h('span', { class: 'text-body-sm text-ink-3' }, [
                        '(',
                        h(UiHighlight, {
                            text: props.keyword,
                            positions: props.keywordPositions,
                        }),
                        ')',
                    ]),
                ]
            :   []),
        ]
    },
})
</script>
