// design-system/src/components/Button.tsx
import type { ReactNode } from 'react'
import type { VariantProps } from 'tailwind-variants'
import { tv } from 'tailwind-variants'

import type { PrimitiveProps } from '../lib/primitive'
import { Primitive } from '../lib/primitive'

const button = tv({
    base: 'inline-flex items-center',
    variants: {
        // Disabled styling is per-tone rather than shared: only primary and
        // ghost ever render disabled, and the two use different opacities.
        tone: {
            primary: [
                'justify-center gap-2 border-none bg-accent px-4.5 py-3',
                'text-body-lg font-extrabold tracking-[-0.01em] text-on-accent',
                '[transition:filter_0.15s,transform_0.08s]',
                'hover:brightness-[1.06] active:scale-[0.99]',
                'disabled:cursor-not-allowed disabled:opacity-45',
            ],
            ghost: [
                'gap-[7px] border border-line-2 bg-transparent px-[15px] py-2.5',
                'text-body font-semibold text-ink',
                'transition-[background] duration-[120ms] hover:bg-surface-2',
                'disabled:cursor-not-allowed disabled:opacity-45',
            ],
            danger: [
                'gap-[7px] border-none bg-red px-4 py-2.5',
                'text-body font-extrabold text-on-red',
                'transition-[filter] duration-150 hover:brightness-[1.08]',
            ],
            link: [
                'gap-1.5 border-none bg-transparent px-0 py-1',
                'text-body-sm font-semibold text-ink-2',
                'transition-[color] duration-[120ms] hover:text-accent-ink',
            ],
        },
        // Declared after `tone` so its padding and size win the merge.
        size: {
            default: '',
            sm: 'px-[11px] py-[7px] text-body-sm',
            lg: 'h-13 w-full text-base',
        },
    },
    defaultVariants: { tone: 'primary', size: 'default' },
})

type ButtonVariants = VariantProps<typeof button>

/**
 * The primary action control. `primary` is the volt-accent call to action,
 * `ghost` the bordered secondary, `danger` the destructive red, and `link` a
 * borderless inline action.
 */
export interface ButtonProps extends PrimitiveProps {
    tone?: ButtonVariants['tone']
    size?: ButtonVariants['size']
    className?: string
    disabled?: boolean
    type?: 'button' | 'submit' | 'reset'
    onClick?: () => void
    children?: ReactNode
}

export function Button({
    as = 'button',
    tone = 'primary',
    size = 'default',
    className,
    ...rest
}: ButtonProps) {
    return (
        <Primitive
            as={as}
            className={button({ tone, size, className })}
            {...rest}
        />
    )
}

// src/lib/ui/Button.svelte
<script lang="ts" module>
	type Variant = 'commit' | 'secondary' | 'destructive' | 'chrome' | 'raised';

	type Look = Variant | 'inert';

	const base =
		'inline-flex items-center justify-center gap-3 select-none focus-ring ' +
		'pointer-fine:transition-[background-color,color,filter] pointer-fine:duration-100 ' +
		'disabled:pointer-events-none';

	const outlined =
		'min-h-row-dense rounded-xl px-5 border border-line hover:bg-hover press:bg-surface-2 press-sink';

	const filled =
		'bg-accent text-on-accent press-sink ' +
		'hover:bg-accent-hover press:[filter:var(--accent-press)] pointer-fine:active:translate-y-px';

	const well = 'border-[1.5px] border-dashed border-line text-ink-faint';

	type Dress = { shape: string; text: string; caps: string };

	const looks: Record<Look, Dress> = {
		commit: {
			shape: `min-h-commit rounded-2xl px-6 ${filled}`,
			text: 'text-xl font-[800]',
			caps: 'text-lg font-[800] tracking-caps'
		},
		secondary: {
			shape: `${outlined} text-ink-muted`,
			text: 'text-md font-bold',
			caps: 'text-md font-extrabold tracking-caps'
		},
		destructive: {
			shape: `${outlined} text-danger`,
			text: 'text-md font-extrabold',
			caps: 'text-md font-extrabold tracking-caps'
		},
		chrome: {
			shape:
				'min-h-chrome rounded-full px-4 border border-line text-ink-muted ' +
				'hover:bg-hover press:bg-surface-2',
			text: 'text-md font-extrabold',
			caps: 'text-sm font-extrabold tracking-caps'
		},
		raised: {
			shape:
				'min-h-row rounded-xl px-5 bg-surface text-ink-muted ' +
				'hover:bg-hover press:bg-surface-2 press-sink',
			text: 'text-md font-bold',
			caps: 'text-sm font-extrabold tracking-caps'
		},
		inert: {
			shape: `min-h-commit rounded-2xl px-6 ${well}`,
			text: 'text-base font-bold',
			caps: 'text-sm font-bold tracking-caps'
		}
	};

	const compacts: Partial<Record<Look, Dress>> = {
		commit: {
			shape: `min-h-row rounded-xl px-5 ${filled}`,
			text: 'text-lg font-[800]',
			caps: 'text-md font-[800] tracking-caps'
		},
		inert: {
			shape: `min-h-row rounded-xl px-5 ${well}`,
			text: 'text-md font-bold',
			caps: 'text-sm font-bold tracking-caps'
		}
	};
</script>

<script lang="ts">
	import type { Snippet } from 'svelte';
	import type { HTMLAnchorAttributes, HTMLButtonAttributes } from 'svelte/elements';
	import { press } from '$lib/ui/press';

	type Props = HTMLButtonAttributes &
		Pick<HTMLAnchorAttributes, 'href' | 'target' | 'rel'> & {
			variant?: Variant;
			caps?: boolean;
			compact?: boolean;
			children: Snippet;
		};

	let {
		variant = 'secondary',
		caps = false,
		compact = false,
		disabled = false,
		href,
		class: klass,
		children,
		...rest
	}: Props = $props();

	const key = $derived(disabled && variant === 'commit' ? ('inert' as const) : variant);
	const look = $derived((compact ? compacts[key] : undefined) ?? looks[key]);
</script>

<svelte:element
	this={href ? 'a' : 'button'}
	{href}
	disabled={href ? undefined : disabled}
	class={[base, look.shape, caps ? look.caps : look.text, klass]}
	{...rest}
	{@attach press()}
>
	{@render children()}
</svelte:element>
